### ISSUE TITLE
Make correct init.c to avoid CRAN warnings

### ISSUE THREAD

**Issue by JohannesFriedrich** [coolbutuseless/simplecall#2]
First of all: 
Thank you very much for this great repository, I learned so much here for my R-packages using pure C-Code!

One of these packages is on CRAN (https://cran.r-project.org/package=qoi) uses your template here but had some warnings when using GCC compiler in init.c: "function declaration isn't a prototype"

The solution is to add all parameters in the prototype definition:

`extern SEXP add_(SEXP,SEXP);`

I prepared a PR

**Comment by coolbutuseless** [comment]
Thanks for this. Finally got around to looking at this!
